[workspace]
members = ["crates/glm", "crates/tui"]
default-members = ["crates/tui"]
resolver = "2"

[workspace.dependencies]
glm = { path = "crates/glm" }
anyhow = "1.0.80"
tokio = { version = "1.36.0", features = ["full"] }
